### ISSUE TITLE
Fehler

### ISSUE THREAD

**Issue by AndyLiebe** [haggybear/plesk-dcp#1]
No connection.

**Comment by ibrauns** [comment]
Same issue here. I solved that with patching sh/dcp_dyndns.sh line 29:

`if [ "$1" = "configs" ]; then
cat /etc/psa/.psa.shadow
echo 
grep PRODUCT_ROOT_D /etc/psa/psa.conf | sed s/^[t]*[A-Z_]*[t]*//
grep HTTPD_VHOSTS_D /etc/psa/psa.conf | sed s/^[t]*[A-Z_]*[t]*//
fi`

The problem is different default behavior of "echo" command in bash. http://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo/219274#219274

**Comment by haggybear** [comment]
Wow, thanks. 
I'll implement your fix!


-Haggy

----- Original-Nachricht -----
Von: ibrauns <notifications@github.com>
An: haggybear/plesk-dcp <plesk-dcp@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Datum: Fr, 24 Feb 2017 9:52
Betreff: Re: [haggybear/plesk-dcp] Fehler (#1)
Same issue here. I solved that with patching sh/dcp_dyndns.sh line 29:
if [ "$1" = "configs" ]; then cat /etc/psa/.psa.shadow echo grep PRODUCT_ROOT_D /etc/psa/psa.conf | sed s/^[t]*[A-Z_]*[t]*// grep HTTPD_VHOSTS_D /etc/psa/psa.conf | sed s/^[t]*[A-Z_]*[t]*// fi

The problem is different default behavior of "echo" command in bash. http://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo/219274#219274
?
